# src/OC/PlatformBundle/Resources/config/services.yml
parameters:
    mon_parametre: ma_valeur

services:
    oc_platform.doctrine.notification:
        class: OC\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }